name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: davidstone/cmake_strict_defaults/.github/workflows/build-and-test.yml@latest
